const test=require('node:test'),assert=require('node:assert/strict');
const {makeAuth,hash,cookie,SESSION,FLOW}=require('../server/auth');
const {createHandler}=require('../server/sync-handler');
const Core=require('../dist/core'),Sets=require('../dist/collections');
function fixture(){const maps={};const db={collection(name){const m=maps[name]||=(new Map());const matches=(d,q)=>d&&Object.entries(q).every(([k,v])=>v?.$gt?d[k]>v.$gt:d[k]===v);return {createIndex:async()=>{},findOne:async q=>[...m.values()].find(d=>matches(d,q))||null,findOneAndDelete:async q=>{const d=[...m.values()].find(d=>matches(d,q));if(d)m.delete(d._id);return d||null;},deleteOne:async q=>m.delete(q._id),insertOne:async d=>{if(m.has(d._id))throw Object.assign(Error(),{code:11000});m.set(d._id,structuredClone(d));},updateOne:async(q,u)=>{const d=m.get(q._id);if(!matches(d,q))return {matchedCount:0};Object.assign(d,u.$set);return {matchedCount:1};}};}};const env={google_oauth_client_id:'client',google_oauth_client_secret:'secret',MONGODB_URI:'test',PAROLE_SYNC_KEY:'k'.repeat(40),PAROLE_AUTH_ORIGIN:'https://app.example'};let params,nonce;const client={generateAuthUrl:p=>{params=p;nonce=p.nonce;return 'https://accounts.google.com/test';},getToken:async()=>({tokens:{id_token:'signed'}}),verifyIdToken:async()=>({getPayload:()=>({sub:'123',nonce,email_verified:true,email:'a@example.com',name:'A'})})};const handler=makeAuth({getDatabase:async()=>db,env,clientFactory:()=>client});return {db,env,handler,params:()=>params};}
async function call(handler,action,method='GET',headers={},body){const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.body=v;return this;},redirect(n,url){this.code=n;this.url=url;return this;},end(){return this;}};const query=typeof action==='string'?{action}:action;await handler({query,method,headers,body},res);return res;}
test('OAuth state is bound to browser, single-use, and session uses secure HttpOnly cookie',async()=>{const f=fixture();const login=await call(f.handler,'login');assert.equal(login.code,302);const state=f.params().state;assert.equal(f.params().code_challenge_method,'S256');assert.deepEqual(f.params().scope,['openid','email','profile']);let r=await call(f.handler,{action:'callback/google',state,code:'test'});assert.match(r.url,/cancelled/);r=await call(f.handler,{action:'callback/google',state,code:'test'},'GET',{cookie:FLOW+'='+state});assert.equal(r.url,'https://app.example/');assert.match(r.headers['Set-Cookie'][0],/HttpOnly; Secure; SameSite=Lax/);const authCookie=r.headers['Set-Cookie'][0].split(';')[0];const who=await call(f.handler,'session','GET',{cookie:authCookie});assert.equal(who.body.user.id,'google-123');assert.equal((await call(f.handler,{action:'callback/google',state,code:'test'},'GET',{cookie:FLOW+'='+state})).url,'https://app.example/?auth_error=expired');assert.equal((await call(f.handler,'logout','POST',{cookie:authCookie,origin:'https://evil.example'})).code,403);await call(f.handler,'logout','POST',{cookie:authCookie,origin:'https://app.example'});assert.equal((await call(f.handler,'session','GET',{cookie:authCookie})).body.user,null);});
test('migration requires session and legacy secret, copies once without deleting legacy',async()=>{const f=fixture(),secret='a'.repeat(43);await f.db.collection('authSessions').insertOne({_id:hash(secret),userId:'google-1',expiresAt:new Date(Date.now()+10000)});const state=Sets.initial([],Core);await f.db.collection('study').insertOne({_id:'personal',revision:12,state});const headers={cookie:SESSION+'='+secret,origin:'https://app.example'};assert.equal((await call(f.handler,'migrate','POST',headers)).code,403);headers.authorization='Bearer '+f.env.PAROLE_SYNC_KEY;assert.equal((await call(f.handler,'migrate','POST',headers)).code,200);assert.deepEqual((await f.db.collection('study').findOne({_id:'google-1'})).state,state);assert.equal((await f.db.collection('study').findOne({_id:'personal'})).revision,12);assert.equal((await call(f.handler,'migrate','POST',headers)).code,409);});
test('account sync cannot read or overwrite another account or accept cross-site writes',async()=>{const f=fixture(),state=Sets.initial([],Core);await f.db.collection('study').insertOne({_id:'google-2',revision:1,state});const handler=createHandler({getCollection:async()=>f.db.collection('study'),getSession:async()=>({userId:'google-1'}),env:f.env});const headers={origin:'https://app.example','x-parole-account':'google-2','content-type':'application/json'};assert.equal((await call(handler,'','GET',headers)).code,401);headers['x-parole-account']='google-1';assert.equal((await call(handler,'','GET',headers)).body.state,null);assert.equal((await call(handler,'','PUT',{...headers,origin:'https://evil.example'},{revision:0,state})).code,403);assert.equal((await call(handler,'','PUT',headers,{revision:0,state})).code,200);assert.equal((await f.db.collection('study').findOne({_id:'google-2'})).revision,1);});
