const test=require('node:test');const assert=require('node:assert/strict');
const Core=require('../dist/core.js'),Sets=require('../dist/collections.js');
const {createHandler}=require('../server/sync-handler.js');
const Sync=require('../dist/sync.js');
test('database diagnostics classify nested errors without exposing driver secrets',()=>{const {databaseFailure}=require('../server/sync-handler.js');for(const [error,code] of [[{code:18,message:'secret'},'DB_AUTH'],[{code:13},'DB_PERMISSION'],[{name:'MongoParseError',message:'secret'},'DB_URI'],[{code:'ENOTFOUND'},'DB_DNS'],[{name:'MongoServerSelectionError',reason:{servers:new Map([['host',{error:{code:18,message:'secret'}}]])}},'DB_AUTH'],[{name:'MongoServerSelectionError'},'DB_NETWORK'],[Error('secret'),'DB_UNAVAILABLE']]){const result=databaseFailure(error);assert.equal(result.code,code);assert.ok(!JSON.stringify(result).includes('secret'));}});
const initial=()=>Sets.initial([],Core);
function fixture(){let doc=null;const col={findOne:async()=>doc,insertOne:async d=>{if(doc)throw Object.assign(Error(),{code:11000});doc=d;},updateOne:async(q,u)=>{if(doc?.revision!==q.revision)return {matchedCount:0};doc={...doc,...u.$set};return {matchedCount:1};}};const key='a'.repeat(64);const env={MONGODB_URI:'test',PAROLE_SYNC_KEY:key,ALLOWED_ORIGINS:'https://app.example'};const handler=createHandler({getCollection:async()=>col,env});return {key,handler};}
async function call(f,method,body,headers={}){const r={headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;},end(){return this;}};await f.handler({method,body,headers:{origin:'https://app.example',authorization:'Bearer '+f.key,'content-type':'application/json',...headers}},r);return r;}
test('authentication, CORS and fail-closed configuration',async()=>{const f=fixture();assert.equal((await call(f,'GET',null,{authorization:'wrong'})).statusCode,401);assert.equal((await call(f,'GET',null,{origin:'https://evil.example'})).statusCode,403);assert.equal((await call(f,'OPTIONS')).statusCode,204);assert.equal((await call(f,'GET')).body.revision,0);});
test('atomic revisions reject competing writes and malformed records',async()=>{const f=fixture(),state=initial();assert.equal((await call(f,'PUT',{revision:0,state})).statusCode,200);assert.equal((await call(f,'PUT',{revision:0,state})).statusCode,409);assert.equal((await call(f,'PUT',{revision:1,state:{...state,history:[{id:'bad',at:1,score:9}]}})).statusCode,400);assert.equal((await call(f,'GET')).body.revision,1);assert.equal((await call(f,'PUT',{revision:1,state})).body.revision,2);assert.equal((await call(f,'PUT',{revision:1,state})).statusCode,409);});
test('server whitelist excludes credentials, draft and unknown properties',async()=>{const f=fixture();const state={...initial(),apiKey:'never store',syncKey:'secret',draft:{answer:'draft'}};await call(f,'PUT',{revision:0,state});const data=(await call(f,'GET')).body.state;assert.equal(data.apiKey,undefined);assert.equal(data.syncKey,undefined);assert.equal(data.draft,null);});
test('conflict policy preserves new local and remote edits; canonical hash ignores drafts',async()=>{assert.equal(Sync.decide('new-local','new-remote',{hash:'old',revision:2},3),'conflict');assert.equal(Sync.decide('old','new',{hash:'old',revision:2},3),'pull');assert.equal(Sync.decide('new','old',{hash:'old',revision:2},2),'push');assert.equal(Sync.decide('new','remote',null,2),'conflict');assert.equal(Sync.decide('new',null,{hash:'old',revision:2},0),'conflict');const state=initial();assert.equal(await Sync.fingerprint(state),await Sync.fingerprint({...state,draft:{answer:'hello'}}));assert.throws(()=>Sync.endpoint('http://example.com'));assert.throws(()=>Sync.endpoint('https://user:pass@example.com'));});
test('client uploads then pulls, but pauses for conflicting edits',async()=>{const f=fixture(),data=new Map();const storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};let state=initial(),conflict;const client=Sync.create({storage,getState:()=>state,applyState:v=>state=v,validate:v=>Sets.validate(v,[],Core),onConflict:v=>conflict=v,fetchImpl:async(u,o)=>{const r=await call(f,o.method,o.body?JSON.parse(o.body):undefined,{authorization:o.headers.Authorization});return {ok:r.statusCode===200,status:r.statusCode,json:async()=>r.body};}});client.connect('https://backend.example',f.key);await client.sync();assert.equal((await call(f,'GET')).body.revision,1);let remote={...initial(),settings:{goal:30,time:'20:00'}};await call(f,'PUT',{revision:1,state:remote});await client.sync();assert.equal(state.settings.goal,30);state.settings.goal=40;remote.settings.goal=50;await call(f,'PUT',{revision:2,state:remote});await client.sync();assert.ok(conflict);assert.equal(state.settings.goal,40);assert.equal((await call(f,'GET')).body.state.settings.goal,50);await client.sync('push');assert.equal((await call(f,'GET')).body.state.settings.goal,40);client.disconnect();assert.equal(data.has(Sync.CONFIG),false);});
